version: '3.4'

services:

  flask-blog-svc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - flask-blog-db
    volumes:
      - .:/app
    restart: always
    ports: 
      - "8080:8080"


  flask-blog-db:
    image: mysql:5.7
    ports: 
      - "32000:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: test_pwFROM python:3.7
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pw
    volumes: 
      - db-data:/var/lib/mysql       

      
volumes: 
  db-data:       